version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Check Java Version
          command: java -version

      - run:
          name: Compile Java Files
          command: javac Arrays/*.java

      - run:
          name: Run MatrixMultiplication
          command: java -cp Arrays MatrixMultiplication

      - run:
          name: Run RotateArray
          command: java -cp Arrays RotateArray

      - run:
          name: Run ReverseNumber
          command: java -cp Arrays reversenumber

workflows:
  version: 2
  java_dsa_pipeline:
    jobs:
      - build
