version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Compile DSAproblems1.java
          command: javac Arrays/DSAproblems1.java

      - run:
          name: Run DSAproblems1
          command: java -cp Arrays DSAproblems1

workflows:
  version: 2
  build_and_run:
    jobs:
      - build
